// Two jobs, both done before the crate compiles.
//
// 1. Embeds the Windows executable icon and version metadata. The icon carries
//    the lacodda line mark at three levels — the filled tile at the smallest
//    sizes, the plated mark above them — so Explorer, the taskbar and the
//    titlebar each get the one that reads at their size. See `src/icon.rs`,
//    which holds that rule with a test, and `docs/export-assets.mjs`, which
//    builds the container.
//
// 2. Turns the line's design tokens into Rust. `assets/dowel/palette.json` is
//    every colour of the dowel theme resolved for nitid's accent, in both
//    themes; `assets/dowel/tokens.json` carries the scales — radius, type,
//    motion. Both are copied verbatim from a published `dowel-ui` release (the
//    version is inside them, and CI compares them against that release byte
//    for byte), and this script writes them out as constants. A colour in the
//    interface is a name from here, never a number typed by hand: the file is
//    where the colour lives, so the next dowel release moves nitid with it.
use std::fmt::Write as _;
use std::path::Path;

fn main() {
    // Two conditions, and both are needed.
    //
    // `#[cfg(windows)]` is about the *host*: it decides whether this code is
    // compiled at all, which it must, because `winresource` is a dependency
    // only for the Windows target and naming it elsewhere does not compile.
    //
    // `CARGO_CFG_TARGET_OS` is about the *target*: cross-checking the crate
    // for Linux from a Windows box compiles this file and would otherwise go
    // looking for rc.exe and panic. That is part of why a lint failing only
    // on Linux could not be reproduced locally.
    #[cfg(windows)]
    if std::env::var("CARGO_CFG_TARGET_OS").as_deref() == Ok("windows") {
        println!("cargo:rerun-if-changed=assets/icon.ico");
        winresource::WindowsResource::new()
            .set_icon("assets/icon.ico")
            .compile()
            .expect("failed to embed the Windows resources");
    }

    let out = std::env::var("OUT_DIR").expect("cargo sets OUT_DIR for a build script");
    std::fs::write(Path::new(&out).join("dowel.rs"), dowel()).expect("failed to write the dowel tokens");
}

const PALETTE: &str = "assets/dowel/palette.json";
const TOKENS: &str = "assets/dowel/tokens.json";

/// The generated module: the palette as two constants of one struct, and the
/// scales as plain numbers.
fn dowel() -> String {
    println!("cargo:rerun-if-changed={PALETTE}");
    println!("cargo:rerun-if-changed={TOKENS}");
    let palette = read(PALETTE);
    let tokens = read(TOKENS);

    let stamp = &palette["$extensions"]["com.lacodda.dowel"];
    let version = stamp["version"]
        .as_str()
        .unwrap_or_else(|| panic!("{PALETTE} does not say which dowel-ui it came from"));
    let product = stamp["product"].as_str().unwrap_or_default();
    assert_eq!(product, "nitid", "{PALETTE} is the palette of `{product}`, not of nitid");

    let dark = theme(&palette, "dark");
    let light = theme(&palette, "light");
    let names: Vec<&str> = dark.iter().map(|(name, _)| name.as_str()).collect();
    let light_names: Vec<&str> = light.iter().map(|(name, _)| name.as_str()).collect();
    assert_eq!(names, light_names, "{PALETTE} names different colours in its two themes");

    let mut code = String::new();
    let _ = writeln!(code, "// Generated by build.rs from {PALETTE} and {TOKENS}. Do not edit.");
    let _ = writeln!(code, "\n/// The `dowel-ui` release these values were copied from.");
    let _ = writeln!(code, "pub const VERSION: &str = {version:?};");

    let _ = writeln!(code, "\n/// Every colour of the dowel theme, on nitid's accent. One field per token.");
    let _ = writeln!(code, "#[derive(Clone, Copy, Debug, PartialEq)]\npub struct Palette {{");
    for name in &names {
        let _ = writeln!(code, "    pub {}: egui::Color32,", field(name));
    }
    let _ = writeln!(code, "}}");
    for (constant, colours) in [("DARK", &dark), ("LIGHT", &light)] {
        let _ = writeln!(code, "\npub const {constant}: Palette = Palette {{");
        for (name, [r, g, b, a]) in colours {
            let _ = writeln!(code, "    {}: egui::Color32::from_rgba_unmultiplied_const({r}, {g}, {b}, {a}),", field(name));
        }
        let _ = writeln!(code, "}};");
    }

    // Radius: `md` is the control radius, the rest step around it.
    let _ = writeln!(code, "\n/// Corner radius, in points. `MD` is the control radius.\npub mod radius {{");
    for (step, value) in steps(&tokens["radius"]) {
        let _ = writeln!(code, "    pub const {}: u8 = {};", step_name(&step), pixels(&value, "radius"));
    }
    let _ = writeln!(code, "}}");

    let _ = writeln!(code, "\n/// Type steps, in points: the size and the line height it is set on.\npub mod text {{");
    for (step, value) in steps(&tokens["typography"]) {
        let size = pixels(&value["fontSize"], "typography");
        let leading = pixels(&value["lineHeight"], "typography");
        let _ = writeln!(code, "    pub const {}: (f32, f32) = ({size}.0, {leading}.0);", step_name(&step));
    }
    let _ = writeln!(code, "}}");

    let _ = writeln!(
        code,
        "\n/// Motion, for a transition that should feel like the rest of the line.\npub mod duration {{"
    );
    for (step, value) in steps(&tokens["duration"]) {
        let milliseconds = match value["unit"].as_str() {
            Some("ms") => value["value"].as_f64(),
            Some("s") => value["value"].as_f64().map(|seconds| seconds * 1000.0),
            _ => None,
        }
        .unwrap_or_else(|| panic!("{TOKENS}: duration `{step}` is not in ms or s"));
        let _ = writeln!(
            code,
            "    pub const {}: std::time::Duration = std::time::Duration::from_millis({});",
            step_name(&step),
            milliseconds.round() as u64
        );
    }
    let _ = writeln!(code, "}}");

    code
}

fn read(path: &str) -> serde_json::Value {
    let text = std::fs::read_to_string(path).unwrap_or_else(|error| panic!("{path}: {error}"));
    serde_json::from_str(&text).unwrap_or_else(|error| panic!("{path}: {error}"))
}

/// The colours of one theme, in the order the file gives them.
fn theme(palette: &serde_json::Value, theme: &str) -> Vec<(String, [u8; 4])> {
    let group = palette["color"][theme]
        .as_object()
        .unwrap_or_else(|| panic!("{PALETTE} has no `{theme}` theme"));
    group
        .iter()
        .map(|(name, token)| {
            let hex = token["$value"].as_str().unwrap_or_else(|| panic!("{PALETTE}: `{theme}.{name}` has no value"));
            (
                name.clone(),
                rgba(hex).unwrap_or_else(|| panic!("{PALETTE}: `{theme}.{name}` is `{hex}`, not #rrggbb[aa]")),
            )
        })
        .collect()
}

/// `#rrggbb` or `#rrggbbaa`, the two forms dowel writes.
fn rgba(hex: &str) -> Option<[u8; 4]> {
    let digits = hex.strip_prefix('#')?;
    if !matches!(digits.len(), 6 | 8) || !digits.is_ascii() {
        return None;
    }
    let byte = |at: usize| u8::from_str_radix(digits.get(at..at + 2)?, 16).ok();
    Some([byte(0)?, byte(2)?, byte(4)?, if digits.len() == 8 { byte(6)? } else { 255 }])
}

/// The steps of a token group, skipping the `$type` and `$description` keys.
fn steps(group: &serde_json::Value) -> Vec<(String, serde_json::Value)> {
    group
        .as_object()
        .expect("a token group is an object")
        .iter()
        .filter(|(key, _)| !key.starts_with('$'))
        .map(|(key, token)| (key.clone(), token["$value"].clone()))
        .collect()
}

/// A dimension in `px`. A `rem` here would need a root size nitid does not
/// have, so it stops the build rather than being guessed at.
fn pixels(value: &serde_json::Value, group: &str) -> u64 {
    assert_eq!(value["unit"].as_str(), Some("px"), "{TOKENS}: a {group} step is not in px");
    value["value"].as_f64().map(|number| number.round() as u64).expect("a dimension has a number")
}

/// `line-2` → `line_2`: a token name as a Rust field.
fn field(name: &str) -> String {
    name.replace('-', "_")
}

/// `2xl` → `XXL`, `md` → `MD`: a scale step as a Rust constant.
fn step_name(step: &str) -> String {
    let step = step.replace('-', "_").to_uppercase();
    match step.strip_prefix('2') {
        Some(rest) => format!("X{rest}"),
        None => step,
    }
}
